export const FrontDeskPermissions = {
  RESERVATION_VIEW: 'FRONT_DESK.RESERVATION_VIEW',
  RESERVATION_CREATE: 'FRONT_DESK.RESERVATION_CREATE',
  RESERVATION_EDIT: 'FRONT_DESK.RESERVATION_EDIT',
  RESERVATION_CANCEL: 'FRONT_DESK.RESERVATION_CANCEL',
  STAY_CHECKIN: 'FRONT_DESK.STAY_CHECKIN',
  STAY_CHECKOUT: 'FRONT_DESK.STAY_CHECKOUT',
  ROOM_ASSIGN: 'FRONT_DESK.ROOM_ASSIGN',
  GUEST_VIEW: 'FRONT_DESK.GUEST_VIEW',
  GUEST_CREATE: 'FRONT_DESK.GUEST_CREATE',
  GUEST_EDIT: 'FRONT_DESK.GUEST_EDIT',
  SHIFT_HANDOVER_CREATE: 'FRONT_DESK.SHIFT_HANDOVER_CREATE',
  CONFIRMATION_SEND: 'FRONT_DESK.CONFIRMATION_SEND',
  PAYMENT_VIEW_SUMMARY: 'FRONT_DESK.PAYMENT_VIEW_SUMMARY',
  DISCOUNT_REQUEST: 'FRONT_DESK.DISCOUNT_REQUEST',
  REFUND_REQUEST: 'FRONT_DESK.REFUND_REQUEST',
  OVERRIDE_REQUEST: 'FRONT_DESK.OVERRIDE_REQUEST',
} as const;

export type FrontDeskPermission =
  (typeof FrontDeskPermissions)[keyof typeof FrontDeskPermissions];
