export const KitchenPermissions = {
  MENU_VIEW: 'KITCHEN.MENU_VIEW',
  MENU_MANAGE: 'KITCHEN.MENU_MANAGE',
  ORDER_VIEW: 'KITCHEN.ORDER_VIEW',
  ORDER_CREATE: 'KITCHEN.ORDER_CREATE',
  ORDER_MODIFY: 'KITCHEN.ORDER_MODIFY',
  ORDER_UPDATE_STATUS: 'KITCHEN.ORDER_UPDATE_STATUS',
  ORDER_CANCEL: 'KITCHEN.ORDER_CANCEL',
  CHARGE_POST: 'KITCHEN.CHARGE_POST',
  REPORTS_VIEW: 'KITCHEN.REPORTS_VIEW',
} as const;

export type KitchenPermission = (typeof KitchenPermissions)[keyof typeof KitchenPermissions];
