export const OwnerPermissions = {
  PORTFOLIO_VIEW: 'OWNER.PORTFOLIO_VIEW',
  PROPERTY_VIEW: 'OWNER.PROPERTY_VIEW',
  FINANCE_VIEW: 'OWNER.FINANCE_VIEW',
  OPERATIONS_VIEW: 'OWNER.OPERATIONS_VIEW',
  EXCEPTIONS_VIEW: 'OWNER.EXCEPTIONS_VIEW',
  AUDIT_VIEW: 'OWNER.AUDIT_VIEW',
  EXPORT: 'OWNER.EXPORT',
  ALERTS_CONFIG: 'OWNER.ALERTS_CONFIG',
  NOTE_CREATE: 'OWNER.NOTE_CREATE',
} as const;

export type OwnerPermission = (typeof OwnerPermissions)[keyof typeof OwnerPermissions];
