export const PlatformAdminPermissions = {
  TENANT_CREATE: 'PLATFORM_ADMIN.TENANT_CREATE',
  TENANT_SUSPEND: 'PLATFORM_ADMIN.TENANT_SUSPEND',
  SUBSCRIPTION_MANAGE: 'PLATFORM_ADMIN.SUBSCRIPTION_MANAGE',
  FEATURE_FLAG_MANAGE: 'PLATFORM_ADMIN.FEATURE_FLAG_MANAGE',
  SYSTEM_VIEW: 'PLATFORM_ADMIN.SYSTEM_VIEW',
  IMPERSONATE: 'PLATFORM_ADMIN.IMPERSONATE',
  AUDIT_VIEW: 'PLATFORM_ADMIN.AUDIT_VIEW',
  USER_RESET: 'PLATFORM_ADMIN.USER_RESET',
} as const;

export type PlatformAdminPermission =
  (typeof PlatformAdminPermissions)[keyof typeof PlatformAdminPermissions];
