export const AuthEvents = {
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_REFRESH_SUCCESS: 'USER_REFRESH_SUCCESS',
  USER_REFRESH_FAILED: 'USER_REFRESH_FAILED',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',
  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_UPDATED: 'STAFF_UPDATED',
  STAFF_DEACTIVATED: 'STAFF_DEACTIVATED',
  STAFF_ACTIVATED: 'STAFF_ACTIVATED',
  STAFF_PASSWORD_RESET: 'STAFF_PASSWORD_RESET',
  STAFF_SOFT_DELETED: 'STAFF_SOFT_DELETED',
  GUEST_REGISTERED: 'GUEST_REGISTERED',
  GUEST_LOGIN_SUCCESS: 'GUEST_LOGIN_SUCCESS',
  GUEST_LOGIN_FAILED: 'GUEST_LOGIN_FAILED',
  GUEST_REFRESH_SUCCESS: 'GUEST_REFRESH_SUCCESS',
  GUEST_REFRESH_FAILED: 'GUEST_REFRESH_FAILED',
  GUEST_LOGOUT: 'GUEST_LOGOUT',
  GUEST_PASSWORD_CHANGED: 'GUEST_PASSWORD_CHANGED',
  MFA_ENROLLMENT_STARTED: 'MFA_ENROLLMENT_STARTED',
  MFA_ENROLLED: 'MFA_ENROLLED',
} as const;

export type AuthEventName = (typeof AuthEvents)[keyof typeof AuthEvents];

