export const FinanceEvents = {
  INVOICE_CREATED: 'INVOICE_CREATED',
  FOLIO_ADJUSTMENT_ADDED: 'FOLIO_ADJUSTMENT_ADDED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  REFUND_EXECUTED: 'REFUND_EXECUTED',
  DAILY_CLOSE_COMPLETED: 'DAILY_CLOSE_COMPLETED',
  FINANCE_SHIFT_HANDOVER_CREATED: 'FINANCE_SHIFT_HANDOVER_CREATED',
} as const;

export type FinanceEventName = (typeof FinanceEvents)[keyof typeof FinanceEvents];
