export const FrontDeskEvents = {
  GUEST_CREATED: 'GUEST_CREATED',
  GUEST_UPDATED: 'GUEST_UPDATED',
  GUEST_PROFILE_UPDATED: 'GUEST_PROFILE_UPDATED',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_UPDATED: 'RESERVATION_UPDATED',
  RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
  CHECKIN_COMPLETED: 'CHECKIN_COMPLETED',
  ROOM_CHANGED: 'ROOM_CHANGED',
  STAY_EXTENDED: 'STAY_EXTENDED',
  CHECKOUT_COMPLETED: 'CHECKOUT_COMPLETED',
  CONFIRMATION_REQUESTED: 'CONFIRMATION_REQUESTED',
  SHIFT_HANDOVER_CREATED: 'SHIFT_HANDOVER_CREATED',
  HOUSEKEEPING_TASK_CREATED: 'HOUSEKEEPING_TASK_CREATED',
} as const;

export type FrontDeskEventName = (typeof FrontDeskEvents)[keyof typeof FrontDeskEvents];
