export const HousekeepingEvents = {
  HOUSEKEEPING_TASK_STARTED: 'HOUSEKEEPING_TASK_STARTED',
  HOUSEKEEPING_TASK_CLEANED: 'HOUSEKEEPING_TASK_CLEANED',
  HOUSEKEEPING_TASK_COMPLETED: 'HOUSEKEEPING_TASK_COMPLETED',
  HOUSEKEEPING_TASK_ASSIGNED: 'HOUSEKEEPING_TASK_ASSIGNED',
  MAINTENANCE_TICKET_CREATED: 'MAINTENANCE_TICKET_CREATED',
  ROOM_STATUS_CHANGED: 'ROOM_STATUS_CHANGED',
} as const;

export type HousekeepingEventName = (typeof HousekeepingEvents)[keyof typeof HousekeepingEvents];
