export const KitchenEvents = {
  MENU_CATEGORY_CREATED: 'MENU_CATEGORY_CREATED',
  MENU_ITEM_CREATED: 'MENU_ITEM_CREATED',
  MENU_ITEM_UPDATED: 'MENU_ITEM_UPDATED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_CANCELLED_WITH_OVERRIDE: 'ORDER_CANCELLED_WITH_OVERRIDE',
  FOLIO_CHARGE_POSTED: 'FOLIO_CHARGE_POSTED',
} as const;

export type KitchenEventName = (typeof KitchenEvents)[keyof typeof KitchenEvents];
