export const ManagerEvents = {
  DISCOUNT_REQUESTED: 'DISCOUNT_REQUESTED',
  DISCOUNT_APPROVED: 'DISCOUNT_APPROVED',
  DISCOUNT_REJECTED: 'DISCOUNT_REJECTED',
  DISCOUNT_APPLIED: 'DISCOUNT_APPLIED',
  REFUND_REQUESTED: 'REFUND_REQUESTED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  REFUND_REJECTED: 'REFUND_REJECTED',
  OVERRIDE_REQUESTED: 'OVERRIDE_REQUESTED',
  OVERRIDE_APPROVED: 'OVERRIDE_APPROVED',
  OVERRIDE_REJECTED: 'OVERRIDE_REJECTED',
  RATEPLAN_CREATED: 'RATEPLAN_CREATED',
  RATEPLAN_UPDATED: 'RATEPLAN_UPDATED',
  INVENTORY_BLOCK_CREATED: 'INVENTORY_BLOCK_CREATED',
  INVENTORY_OVERRIDDEN: 'INVENTORY_OVERRIDDEN',
  RESERVATION_CONFIRMED_BY_MANAGER: 'RESERVATION_CONFIRMED_BY_MANAGER',
  RESERVATION_MARKED_NO_SHOW: 'RESERVATION_MARKED_NO_SHOW',
  RESERVATION_FORCE_CANCELLED: 'RESERVATION_FORCE_CANCELLED',
  DAY_UNLOCKED_BY_MANAGER: 'DAY_UNLOCKED_BY_MANAGER',
  ROOM_STATUS_SET_FOR_ONBOARDING: 'ROOM_STATUS_SET_FOR_ONBOARDING',
} as const;

export type ManagerEventName = (typeof ManagerEvents)[keyof typeof ManagerEvents];
