export const PlatformAdminEvents = {
  TENANT_CREATED: 'TENANT_CREATED',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_REACTIVATED: 'TENANT_REACTIVATED',
  TENANT_PLAN_CHANGED: 'TENANT_PLAN_CHANGED',
  FEATURE_FLAG_UPDATED: 'FEATURE_FLAG_UPDATED',
  IMPERSONATION_STARTED: 'IMPERSONATION_STARTED',
  IMPERSONATION_ENDED: 'IMPERSONATION_ENDED',
  USER_PASSWORD_RESET_BY_PLATFORM: 'USER_PASSWORD_RESET_BY_PLATFORM',
} as const;

export type PlatformAdminEventName =
  (typeof PlatformAdminEvents)[keyof typeof PlatformAdminEvents];
