export const OwnerExceptionType = {
  DAILY_CLOSE_VARIANCE: 'DAILY_CLOSE_VARIANCE',
  DAY_UNLOCKED: 'DAY_UNLOCKED',
  DISCOUNT_APPROVED: 'DISCOUNT_APPROVED',
  REFUND_APPROVED: 'REFUND_APPROVED',
  REFUND_EXECUTED: 'REFUND_EXECUTED',
  INVENTORY_OVERRIDDEN: 'INVENTORY_OVERRIDDEN',
  MULTIPLE_CANCELS_BY_USER: 'MULTIPLE_CANCELS_BY_USER',
  HIGH_MANUAL_ADJUSTMENTS: 'HIGH_MANUAL_ADJUSTMENTS',
  ROOM_STATUS_ANOMALY: 'ROOM_STATUS_ANOMALY',
} as const;

export type OwnerExceptionType =
  (typeof OwnerExceptionType)[keyof typeof OwnerExceptionType];
